"""
Parse pre-formatted aggregated intelligence report messages from Channel A.

These differ from raw single-flow alerts. They already contain a full
market bias report with multiple flow entries, market structure, and a
game plan — generated by an upstream system.

Detection: message starts with "🔴 MARKET BIAS:" or "🟢 MARKET BIAS:"

Entry formats parsed (numbered or bulleted):
  1. 🟢 META 660C AGGR  | $22.37M IV:37%  | Vol/OI 2.7x  | Δ 0.57  | DTE 3  | INSTITUTIONAL
  • 🔴 SPY 686P AGGR  | $582K IV:16%  | Vol/OI 19.5x  | Δ -0.28  | DTE 6  | INSTITUTIONAL
"""

import re
import logging
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)

# ── Entry regex ───────────────────────────────────────────────────────────────
# Matches both numbered (1.) and bulleted (•) flow entries.
_ENTRY_RE = re.compile(
    r"(?:\d+\.\s+|[•·]\s+)"            # "1. " or "• "
    r"(?:[🟢🔴]\s*)?"                    # optional emoji
    r"([A-Z]{1,6})"                      # ticker
    r"\s+(\d+(?:\.\d+)?)(C|P)"           # strike + type
    r"(?:\s+\w+)?"                        # optional label e.g. AGGR
    r"\s*\|\s*\$([0-9,.]+[KMBkmb]?)"     # premium
    r"(?:\s+IV:(\d+(?:\.\d+)?)%)?"       # IV (optional)
    r"\s*\|\s*Vol/OI\s+([\d.]+)x"        # vol/OI
    r"\s*\|\s*Δ\s*([-\d.]+)"             # delta
    r"\s*\|\s*DTE\s+(\d+)"               # DTE
    r"(?:\s*\|\s*(.+))?$",               # tag (optional)
    re.IGNORECASE,
)

_PREMIUM_MULT = {"K": 1_000, "M": 1_000_000, "B": 1_000_000_000}


@dataclass
class FlowEntry:
    ticker: str
    strike: float
    side: str          # "CALL" | "PUT"
    premium_usd: float
    iv_pct: float
    vol_oi_ratio: float
    delta: float
    dte: int
    tag: str


@dataclass
class IntelReport:
    """Parsed aggregated intelligence report."""
    direction: str           # "BULLISH" | "BEARISH" | "NEUTRAL"
    context: str             # everything after "WITH" on the bias line
    bear_pct: int
    bull_pct: int
    confidence: int
    top_overall: list[FlowEntry] = field(default_factory=list)
    top_bears:   list[FlowEntry] = field(default_factory=list)
    top_bulls:   list[FlowEntry] = field(default_factory=list)
    market_structure: list[str] = field(default_factory=list)
    sector_leadership: list[str] = field(default_factory=list)
    game_plan: list[str] = field(default_factory=list)
    quick_read: list[str] = field(default_factory=list)


# ── Detection ─────────────────────────────────────────────────────────────────

def is_aggregated_report(text: str) -> bool:
    """Return True if the message is an aggregated intel report."""
    first = text.strip().splitlines()[0] if text.strip() else ""
    return bool(re.search(r"MARKET BIAS\s*:", first, re.IGNORECASE))


# ── Premium parser ────────────────────────────────────────────────────────────

def _parse_premium(raw: str) -> float:
    raw = raw.replace(",", "").strip()
    suffix = raw[-1].upper() if raw and raw[-1].upper() in _PREMIUM_MULT else ""
    try:
        val = float(raw[:-1] if suffix else raw)
        return val * _PREMIUM_MULT.get(suffix, 1)
    except ValueError:
        return 0.0


# ── Entry parser ──────────────────────────────────────────────────────────────

def _parse_entry(line: str) -> Optional[FlowEntry]:
    m = _ENTRY_RE.search(line)
    if not m:
        return None
    ticker, strike, cp, premium_raw, iv_raw, vol_oi, delta, dte, tag = m.groups()
    return FlowEntry(
        ticker=ticker.upper(),
        strike=float(strike),
        side="CALL" if cp.upper() == "C" else "PUT",
        premium_usd=_parse_premium(premium_raw),
        iv_pct=float(iv_raw) if iv_raw else 0.0,
        vol_oi_ratio=float(vol_oi),
        delta=float(delta),
        dte=int(dte),
        tag=(tag or "").strip(),
    )


# ── Section collector ─────────────────────────────────────────────────────────

def _collect_section_lines(lines: list[str], start_idx: int) -> list[str]:
    """Collect non-empty lines after start_idx until the next section header."""
    result = []
    for line in lines[start_idx + 1:]:
        stripped = line.strip()
        if not stripped:
            continue
        # Stop at next section header (title-case or ALL CAPS word followed by optional emoji)
        if re.match(r"^(Top |Market Structure|Sector|Game Plan|Quick Read)", stripped, re.IGNORECASE):
            break
        result.append(stripped)
    return result


# ── Main parser ───────────────────────────────────────────────────────────────

def parse_intel_report(text: str) -> Optional[IntelReport]:
    """
    Parse an aggregated intelligence report message.
    Returns IntelReport or None if parsing fails.
    """
    lines = [ln for ln in text.strip().splitlines()]

    # ── Bias line ─────────────────────────────────────────────────────────────
    bias_line = lines[0].strip() if lines else ""
    bias_m = re.search(r"MARKET BIAS\s*:\s*(BEARISH|BULLISH|NEUTRAL)", bias_line, re.IGNORECASE)
    if not bias_m:
        logger.debug("intel_parser: no MARKET BIAS line found")
        return None

    direction = bias_m.group(1).upper()
    context_m = re.search(r"WITH\s+(.+)$", bias_line, re.IGNORECASE)
    context = context_m.group(1).strip() if context_m else ""

    # ── Bear/Bull/Confidence ──────────────────────────────────────────────────
    bear_pct = bull_pct = confidence = 0
    for line in lines[1:4]:
        bb_m = re.search(r"Bear\s+(\d+)%.*Bull\s+(\d+)%", line, re.IGNORECASE)
        if bb_m:
            bear_pct = int(bb_m.group(1))
            bull_pct = int(bb_m.group(2))
        conf_m = re.search(r"Confidence\s*:\s*(\d+)", line, re.IGNORECASE)
        if conf_m:
            confidence = int(conf_m.group(1))

    report = IntelReport(
        direction=direction,
        context=context,
        bear_pct=bear_pct,
        bull_pct=bull_pct,
        confidence=confidence,
    )

    # ── Section parsing ───────────────────────────────────────────────────────
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if re.match(r"Top Overall Flow", line, re.IGNORECASE):
            section = _collect_section_lines(lines, i)
            for sl in section:
                e = _parse_entry(sl)
                if e:
                    report.top_overall.append(e)

        elif re.match(r"Top Bears?", line, re.IGNORECASE):
            section = _collect_section_lines(lines, i)
            for sl in section:
                e = _parse_entry(sl)
                if e:
                    report.top_bears.append(e)

        elif re.match(r"Top Bulls?", line, re.IGNORECASE):
            section = _collect_section_lines(lines, i)
            for sl in section:
                e = _parse_entry(sl)
                if e:
                    report.top_bulls.append(e)

        elif re.match(r"Market Structure", line, re.IGNORECASE):
            report.market_structure = _collect_section_lines(lines, i)

        elif re.match(r"Sector", line, re.IGNORECASE):
            report.sector_leadership = _collect_section_lines(lines, i)

        elif re.match(r"Game Plan", line, re.IGNORECASE):
            report.game_plan = _collect_section_lines(lines, i)

        elif re.match(r"Quick Read", line, re.IGNORECASE):
            report.quick_read = _collect_section_lines(lines, i)

        i += 1

    logger.info(
        "intel_parser: parsed aggregated report | direction=%s | confidence=%d "
        "| top_overall=%d | bulls=%d | bears=%d",
        direction, confidence,
        len(report.top_overall), len(report.top_bulls), len(report.top_bears),
    )
    return report
